=== abulanchuk/javaWebDev/Task3/src/main/resources/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.task3.org/candies" xmlns:tns="http://www.task3.org/candies">

    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:sweet" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="base-sweets-type" abstract="true">
        <sequence>
            <element name="name" type="string"/>
            <element name="packing-time" type="date"/>
            <element name="energy" type="positiveInteger"/>
            <element name="sugar" type="positiveInteger"/>
            <element name="butter" type="positiveInteger"/>
            <element name="sweets-value" type="tns:sweets-value"/>
            <element name="production" type="tns:production"/>
        </sequence>
        <attribute name="id" type="tns:candy-id" use="required"/>
        <attribute name="packaging" type="tns:packaging-type" use="optional" default="black"/>
    </complexType>

    <complexType name="candy-type">
        <complexContent>
            <extension base="tns:base-sweets-type">
                <sequence>
                    <element name="candy-type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="choco"/>
                                <enumeration value="lollipop"/>
                                <enumeration value="marmalade"/>
                                <enumeration value="nuts"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="filled" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="chocolate-type">
        <complexContent>
            <extension base="tns:base-sweets-type">
                <sequence>
                    <element name="chocolate-type">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="milk"/>
                                <enumeration value="dark"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="sweets-value">
        <sequence>
            <element name="protein">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="fats">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="carbohydrates">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>

    <simpleType name="production">
        <restriction base="string">
            <enumeration value="Kommunarka"/>
            <enumeration value="Ferrero"/>
            <enumeration value="Storck"/>
            <enumeration value="Mars"/>
            <enumeration value="Ritter"/>
            <enumeration value="Roshen"/>
            <enumeration value="Mondelez"/>
        </restriction>
    </simpleType>

    <simpleType name="packaging-type">
        <restriction base="string">
            <enumeration value="black"/>
            <enumeration value="blue"/>
            <enumeration value="yellow"/>
            <enumeration value="white"/>
            <enumeration value="grey"/>
        </restriction>
    </simpleType>

    <simpleType name="candy-id">
        <restriction base="ID">
            <pattern value="\w{1,30}"/>
        </restriction>
    </simpleType>

    <element name="sweet" type="tns:base-sweets-type" abstract="true"/>
    <element name="candy" type="tns:candy-type" substitutionGroup="tns:sweet"/>
    <element name="chocolate" type="tns:chocolate-type" substitutionGroup="tns:sweet"/>
</schema>

=== abulanchuk/javaWebDev/Task3/src/main/resources/candies_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:c="http://www.task3.org/candies"
         xsi:schemaLocation="http://www.task3.org/candies candies.xsd">

    <chocolate id="ch1">
        <name>Alenka</name>
        <packing-time>2021-05-21</packing-time>
        <energy>560</energy>
        <sugar>30</sugar>
        <butter>20</butter>
        <sweets-value>
            <protein>7.1</protein>
            <fats>35.6</fats>
            <carbohydrates>52.4</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <chocolate-type>milk</chocolate-type>
    </chocolate>

    <candy id="c1" packaging="yellow">
        <name>Ferrero Rocher</name>
        <packing-time>2021-04-01</packing-time>
        <energy>603</energy>
        <sugar>15</sugar>
        <butter>10</butter>
        <sweets-value>
            <protein>8</protein>
            <fats>43</fats>
            <carbohydrates>44</carbohydrates>
        </sweets-value>
        <production>Ferrero</production>
        <candy-type>choco</candy-type>
        <filled>true</filled>
    </candy>

</candies>

=== abulanchuk/javaWebDev/Task3/src/main/resources/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:c="http://www.task3.org/candies"
         xsi:schemaLocation="http://www.task3.org/candies candies.xsd">

    <chocolate id="ch1">
        <name>Alenka</name>
        <packing-time>2021-05-21</packing-time>
        <energy>560</energy>
        <sugar>30</sugar>
        <butter>20</butter>
        <sweets-value>
            <protein>7.1</protein>
            <fats>35.6</fats>
            <carbohydrates>52.4</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <chocolate-type>milk</chocolate-type>
    </chocolate>

    <candy id="c1" packaging="yellow">
        <name>Ferrero Rocher</name>
        <packing-time>2021-04-01</packing-time>
        <energy>603</energy>
        <sugar>15</sugar>
        <butter>10</butter>
        <sweets-value>
            <protein>8</protein>
            <fats>43</fats>
            <carbohydrates>44</carbohydrates>
        </sweets-value>
        <production>Ferrero</production>
        <candy-type>choco</candy-type>
        <filled>true</filled>
    </candy>

    <chocolate id="ch2" packaging="black">
        <name>Mersi</name>
        <packing-time>2020-12-21</packing-time>
        <energy>560</energy>
        <sugar>17</sugar>
        <butter>28</butter>
        <sweets-value>
            <protein>7.6</protein>
            <fats>37.2</fats>
            <carbohydrates>50.8</carbohydrates>
        </sweets-value>
        <production>Storck</production>
        <chocolate-type>dark</chocolate-type>
    </chocolate>

    <candy id="c2">
        <name>Mamba</name>
        <packing-time>2021-10-22</packing-time>
        <energy>389</energy>
        <sugar>16</sugar>
        <butter>3</butter>
        <sweets-value>
            <protein>0.5</protein>
            <fats>5.4</fats>
            <carbohydrates>85.4</carbohydrates>
        </sweets-value>
        <production>Storck</production>
        <candy-type>marmalade</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c3">
        <name>Red had</name>
        <packing-time>2012-04-11</packing-time>
        <energy>538</energy>
        <sugar>13</sugar>
        <butter>10</butter>
        <sweets-value>
            <protein>6.6</protein>
            <fats>30.9</fats>
            <carbohydrates>58.3</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <candy-type>choco</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c4" packaging="blue">
        <name>Bear in the meadow</name>
        <packing-time>2020-06-17</packing-time>
        <energy>543</energy>
        <sugar>20</sugar>
        <butter>12</butter>
        <sweets-value>
            <protein>7.2</protein>
            <fats>32.6</fats>
            <carbohydrates>54.9</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <candy-type>choco</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c5">
        <name>Raffaello</name>
        <packing-time>2010-07-25</packing-time>
        <energy>543</energy>
        <sugar>25</sugar>
        <butter>20</butter>
        <sweets-value>
            <protein>9.3</protein>
            <fats>47.7</fats>
            <carbohydrates>36.8</carbohydrates>
        </sweets-value>
        <production>Ferrero</production>
        <candy-type>choco</candy-type>
        <filled>true</filled>
    </candy>

    <chocolate id="ch3">
        <name>Alpen Gold</name>
        <packing-time>2011-03-01</packing-time>
        <energy>522</energy>
        <sugar>31</sugar>
        <butter>11</butter>
        <sweets-value>
            <protein>5.4</protein>
            <fats>28</fats>
            <carbohydrates>62</carbohydrates>
        </sweets-value>
        <production>Ferrero</production>
        <chocolate-type>milk</chocolate-type>
    </chocolate>

    <candy id="c6">
        <name>Snickers</name>
        <packing-time>1997-04-15</packing-time>
        <energy>250</energy>
        <sugar>17</sugar>
        <butter>18</butter>
        <sweets-value>
            <protein>3.5</protein>
            <fats>13</fats>
            <carbohydrates>30</carbohydrates>
        </sweets-value>
        <production>Mars</production>
        <candy-type>nuts</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c7" packaging="blue">
        <name>Bounty</name>
        <packing-time>2010-10-10</packing-time>
        <energy>485</energy>
        <sugar>24</sugar>
        <butter>16</butter>
        <sweets-value>
            <protein>3.1</protein>
            <fats>25.3</fats>
            <carbohydrates>60</carbohydrates>
        </sweets-value>
        <production>Mars</production>
        <candy-type>choco</candy-type>
        <filled>false</filled>
    </candy>

    <chocolate id="ch4">
        <name>Ritter sport</name>
        <packing-time>2021-05-24</packing-time>
        <energy>572</energy>
        <sugar>13</sugar>
        <butter>22</butter>
        <sweets-value>
            <protein>5</protein>
            <fats>37</fats>
            <carbohydrates>53</carbohydrates>
        </sweets-value>
        <production>Ritter</production>
        <chocolate-type>dark</chocolate-type>
    </chocolate>

    <candy id="c8">
        <name>Crazy bee</name>
        <packing-time>2021-12-14</packing-time>
        <energy>318</energy>
        <sugar>19</sugar>
        <butter>2</butter>
        <sweets-value>
            <protein>0</protein>
            <fats>0.2</fats>
            <carbohydrates>79</carbohydrates>
        </sweets-value>
        <production>Roshen</production>
        <candy-type>marmalade</candy-type>
        <filled>true</filled>
    </candy>

    <candy id="c9">
        <name>Grillash</name>
        <packing-time>2018-08-23</packing-time>
        <energy>418</energy>
        <sugar>15</sugar>
        <butter>12</butter>
        <sweets-value>
            <protein>4.4</protein>
            <fats>13.8</fats>
            <carbohydrates>68.6</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <candy-type>nuts</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c10">
        <name>bird milk</name>
        <packing-time>2021-11-18</packing-time>
        <energy>230</energy>
        <sugar>27</sugar>
        <butter>18</butter>
        <sweets-value>
            <protein>5.8</protein>
            <fats>12.8</fats>
            <carbohydrates>23</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <candy-type>choco</candy-type>
        <filled>false</filled>
    </candy>

    <candy id="c11">
        <name>Chupa Chups</name>
        <packing-time>1987-04-13</packing-time>
        <energy>538</energy>
        <sugar>30</sugar>
        <butter>1</butter>
        <sweets-value>
            <protein>8.7</protein>
            <fats>34.3</fats>
            <carbohydrates>49.5</carbohydrates>
        </sweets-value>
        <production>Kommunarka</production>
        <candy-type>lollipop</candy-type>
        <filled>false</filled>
    </candy>

    <chocolate id="ch5">
        <name>Milka</name>
        <packing-time>2021-09-17</packing-time>
        <energy>532</energy>
        <sugar>27</sugar>
        <butter>30</butter>
        <sweets-value>
            <protein>6.1</protein>
            <fats>29</fats>
            <carbohydrates>59</carbohydrates>
        </sweets-value>
        <production>Mondelez</production>
        <chocolate-type>milk</chocolate-type>
    </chocolate>
</candies>
